# Site settings
title: hidmic's den
url: 'http://hidmic.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Michel Hidalgo'
  description: 'Robotics Software Engineer'
  email: hid.michel@gmail.com
  github_username: hidmic
  linkedin_username: michel-hidalgo
  resume_url: https://github.com/hidmic/resume/releases/latest/download/resume.en.pdf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock']
